package udv.compi;

import java_cup.runtime.*;

class Parser;

terminal LLA, LLC, CA, CC, DP, COMMA, COMILLA;
terminal String VAL, ID;
terminal String NUM;

non terminal S, L, LP, V;

start with L;

L ::= L COMMA NUM:n{: System.out.print(",");
				if (Integer.parseInt(n)> 10){
					System.out.print("error");
				}else{
					System.out.print(n);
				}
	:}
	|NUM:n {: if (Integer.parseInt(n)> 10){
					System.out.print("error");
				}else{
					System.out.print(n);
				}
			:};
			
	